# Grafana数据源配置
# CodeStudio Pro Ultimate 3.0 Prometheus数据源

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}
    
  - name: Prometheus-Alertmanager
    type: prometheus
    access: proxy
    url: http://localhost:9093
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 30s
      timeInterval: 15s
    secureJsonData: {}
